POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Admin",
    "email": "admin@user.com",
    "password": "admin",
    "role": "ADMIN"
}

###
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbWEyczBkMmMwMDAwdjBoc2d1OWZydWtxIiwibmFtZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkB1c2VyLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc0NTk0NzUyMywiZXhwIjoxNzQ1OTU0NzIzfQ.I--G7pFwtFlSFzpOzFu9hY73nnm8iOXl89qtZyAzPrk

###
GET http://localhost:3000/users/cma2s0d2c0000v0hsgu9frukq

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "admin@user.com",
    "password": "admin"
}

